# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '03LobbyPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1046, 740)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.qrCode = QtWidgets.QLabel(Form)
        self.qrCode.setText("")
        self.qrCode.setScaledContents(True)
        self.qrCode.setObjectName("qrCode")
        self.horizontalLayout_3.addWidget(self.qrCode)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.playerView = QtWidgets.QListView(Form)
        self.playerView.setModelColumn(0)
        self.playerView.setObjectName("playerView")
        self.verticalLayout.addWidget(self.playerView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btn_Zurueck = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_Zurueck.setFont(font)
        self.btn_Zurueck.setObjectName("btn_Zurueck")
        self.btn_Update = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_Update.setFont(font)
        self.btn_Update.setObjectName("btn_Update")
        self.btn_Weiter = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_Weiter.setFont(font)
        self.btn_Weiter.setObjectName("btn_Weiter")
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Verbundene Spieler"))
        self.btn_Zurueck.setText(_translate("Form", "Zurück"))
        self.btn_Update.setText(_translate("Form", "Aktuallisieren"))
        self.btn_Weiter.setText(_translate("Form", "Weiter"))
